### PR TITLE
added swagger

### PR DESCRIPTION
**Pull request by jstaerk**
Access http://127.0.0.1:6000/swagger for the demo (HTML5) client. Feel free to click VeraPDF, /api/validate/{profileId} Post, "Try it out" to upload a file to validate. Access  
http://127.0.0.1:6000/swagger.json for the openapi definition file, which can be pasted in https://editor.swagger.io/ to generate clients in some computer languages as well.

### CODE REVIEW

**Comment by carlwilson** [comment]
@jstaerk I've fixed the Dropbox versioning conflicts here so this should build now. Will take a closer look once the build completes and the tests pass.

**Comment by batlicka** [comment]
There is in last build probbably some bug. After performing command "java -jar verapdf-rest-0.1.0-SNAPSHOT.jar server" I am obtaining " java.lang.IllegalStateException: You need to provide an instance of SwaggerBundleConfiguration"

C:\Users\vojta\IdeaProjects\veraPDF-rest\target>java -jar verapdf-rest-0.1.0-SNAPSHOT.jar server
INFO  [2021-02-02 10:50:56,101] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-02-02 10:50:56,108] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-02-02 10:50:56,109] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: css for path /css/*
INFO  [2021-02-02 10:50:56,159] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: js for path /js/*
INFO  [2021-02-02 10:50:56,161] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: img for path /img/*
java.lang.IllegalStateException: You need to provide an instance of SwaggerBundleConfiguration
        at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:59)
        at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at org.verapdf.rest.app.VeraPdfRestApplication.main(VeraPdfRestApplication.java:45)

**Comment by alexis-via** [comment]
I have the same problem as @batlicka "java.lang.IllegalStateException: You need to provide an instance of SwaggerBundleConfiguration" with exactly the same Java backtrace. I'm on Ubuntu 20.04 LTS with openjdk 11 (same with openjdk 14).

If I checkout the commit 7f1970f81d3d55e1804dafbc60596d3f2c5cfb38 (the commit right before the merge of this PR) and I rebuild (mvn clean package), then I can start veraPDF-rest without problems.
@jstaerk What do you think of this problem ?

**Comment by alexis-via** [comment]
I opened a new issue about this, to make it easier for other users to find the problem and get info about the workaround.

**Pull request merged**
